# Generated by Django 2.2.12 on 2020-09-07 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200907_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Category'),
        ),
    ]
